name: docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions/docs@v1
        with:
          extras: dev

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: compas-dev/compas-actions/docs@v1
        with:
          deploy: true
          extras: dev
