name: prepare release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Semantic version component to bump
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions/release-pr@v1
        with:
          release-type: ${{ inputs.release-type }}
          github-token: ${{ github.token }}
